using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Etlap
{
	/// <summary>
	/// Interaction logic for MainWindow.xaml
	/// </summary>
	public partial class MainWindow : Window
	{
		FoodService foodServ;
		public MainWindow()
		{
			InitializeComponent();
			foodServ = new FoodService();
			Read();
		}

		private void Read()
		{
			tableGrid.ItemsSource = foodServ.Fetch();
			tableGrid.AutoGeneratedColumns += tableGrid_OnAutoGeneratedColumns;

		}

		private void tableGrid_OnAutoGeneratedColumns(object? sender, EventArgs e)
		{
			tableGrid.Columns[2].Visibility = Visibility.Hidden;
		}

		private void tableGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
		{
			Food selected = tableGrid.SelectedItem as Food;
			if (selected != null)
			{
				descMain.Text = selected.Desc;
			}
		}

		private void Add_Click(object sender, RoutedEventArgs e)
		{
			FoodForm form = new FoodForm(foodServ);
			form.Closed += (_, _) =>
			{
				Read();
			};
			form.ShowDialog();
		}

		private void Modify_Click(object sender, RoutedEventArgs e)
		{
			int amount = Int32.Parse(increaseAmount.Text);
			string type = increaseType.Text;
			Food selec = tableGrid.SelectedItem as Food;
			if (selec == null)
			{
				MessageBoxResult selecButton = MessageBox.Show($"Are you sure you want to increase all prices by {amount}{type}?", "Confirm?", MessageBoxButton.YesNo);
				if (selecButton == MessageBoxResult.Yes)
				{
					if (foodServ.ModifyAll(amount, type)) { MessageBox.Show("Update successful."); }
					else { MessageBox.Show("Error during deletion; item not found."); }
					Read();
				}
			}
			else
			{
				MessageBoxResult selecButton = MessageBox.Show($"Are you sure you want to delete {selec.Name}?", "Confirm?", MessageBoxButton.YesNo);
				if (selecButton == MessageBoxResult.Yes)
				{
					if (foodServ.Delete(selec.ID)) { MessageBox.Show("Deletion successful."); }
					else { MessageBox.Show("Error during deletion; item not found."); }
					Read();
				}
			}
		}

		private void Delete_Click(object sender, RoutedEventArgs e)
		{
			Food selec = tableGrid.SelectedItem as Food;
			if (selec == null)
			{
				MessageBox.Show("Select a menu item before attempting deletion!");
				return;
			}
			else
			{
				MessageBoxResult selecButton = MessageBox.Show($"Are you sure you want to delete {selec.Name}?", "Confirm?", MessageBoxButton.YesNo);
				if (selecButton == MessageBoxResult.Yes)
				{
					if (foodServ.Delete(selec.ID)) { MessageBox.Show("Deletion successful."); }
					else { MessageBox.Show("Error during deletion; item not found."); }
					Read();
				}
			}
		}
	}
}
